# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `buftok` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

class BufferedTokenizer
  def initialize(delimiter = T.unsafe(nil)); end

  def extract(data); end
  def flush; end
end
