# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `elasticsearch` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module Elastic
  class << self
    def client_meta_version; end
  end
end

Elastic::ELASTICSEARCH_SERVICE_VERSION = T.let(T.unsafe(nil), Array)

module Elasticsearch
end

class Elasticsearch::Client
  include(::Elasticsearch::API)
  include(::Elasticsearch::API::Shutdown)
  include(::Elasticsearch::API::Features)
  include(::Elasticsearch::API::DanglingIndices)
  include(::Elasticsearch::API::Remote)
  include(::Elasticsearch::API::Cat)
  include(::Elasticsearch::API::Tasks)
  include(::Elasticsearch::API::Snapshot)
  include(::Elasticsearch::API::Ingest)
  include(::Elasticsearch::API::Indices)
  include(::Elasticsearch::API::Nodes)
  include(::Elasticsearch::API::Cluster)
  include(::Elasticsearch::API::Actions)
  include(::Elasticsearch::API::Common)

  def initialize(arguments = T.unsafe(nil), &block); end

  def method_missing(name, *args, &block); end
  def transport; end
  def transport=(_arg0); end

  private

  def elasticsearch_validation_request; end
  def verify_elasticsearch; end
  def verify_with_version_or_header(body, version, headers); end
end

Elasticsearch::NOT_ELASTICSEARCH_WARNING = T.let(T.unsafe(nil), String)

Elasticsearch::NOT_SUPPORTED_ELASTICSEARCH_WARNING = T.let(T.unsafe(nil), String)

Elasticsearch::SECURITY_PRIVILEGES_VALIDATION_WARNING = T.let(T.unsafe(nil), String)

class Elasticsearch::UnsupportedProductError < ::StandardError
  def initialize(message = T.unsafe(nil)); end
end

Elasticsearch::VERSION = T.let(T.unsafe(nil), String)

Elasticsearch::YOU_KNOW_FOR_SEARCH = T.let(T.unsafe(nil), String)
