# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `equalizer` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class Equalizer < ::Module
  def initialize(*keys); end

  private

  def define_cmp_method; end
  def define_hash_method; end
  def define_inspect_method; end
  def define_methods; end
  def included(descendant); end
end

module Equalizer::Methods
  def ==(other); end
  def eql?(other); end
end
