# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `foundation-icons-sass-rails` gem.
# Please instead update this file by running `bin/tapioca gem foundation-icons-sass-rails`.

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails.rb#1
module Foundation; end

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails.rb#2
module Foundation::Icons; end

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails.rb#3
module Foundation::Icons::Sass; end

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails.rb#4
module Foundation::Icons::Sass::Rails; end

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails/engine.rb#5
class Foundation::Icons::Sass::Rails::Engine < ::Rails::Engine; end

# source://foundation-icons-sass-rails//lib/foundation-icons-sass-rails/version.rb#5
Foundation::Icons::Sass::Rails::VERSION = T.let(T.unsafe(nil), String)
