# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `guard-rubocop` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Guard
  extend ::Guard::Deprecated::Guard::ClassMethods
  extend ::Guard::Internals::Helpers

  class << self
    def async_queue_add(changes); end
    def init(cmdline_options); end
    def interactor; end
    def listener; end
    def queue; end
    def setup(cmdline_options = T.unsafe(nil)); end
    def state; end

    private

    def _evaluate(options); end
    def _guardfile_deprecated_check(modified); end
    def _listener_callback; end
    def _pluginless_guardfile?; end
    def _relative_pathnames(paths); end
    def _relevant_changes?(changes); end
  end
end

class Guard::RuboCop < ::Guard::Plugin
  def initialize(options = T.unsafe(nil)); end

  def failed_paths; end
  def options; end
  def reload; end
  def run_all; end
  def run_on_additions(paths); end
  def run_on_modifications(paths); end
  def start; end

  private

  def clean_paths(paths); end
  def included_in_other_path?(target_path, other_paths); end
  def inspect_with_rubocop(paths = T.unsafe(nil)); end
  def run_partially(paths); end
  def smart_path(path); end
end

class Guard::RuboCop::Runner
  def initialize(options); end

  def args_specified_by_user; end
  def build_command(paths); end
  def failed_paths; end
  def include_formatter_for_console?(cli_args); end
  def json_file_path; end
  def notify(passed); end
  def open_launchy_if_needed; end
  def pluralize(number, thing, options = T.unsafe(nil)); end
  def result; end
  def run(paths = T.unsafe(nil)); end
  def should_add_default_formatter_for_console?; end
  def summary_text; end
end
