# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `selectize-rails` gem.
# Please instead update this file by running `bin/tapioca gem selectize-rails`.


# source://selectize-rails//lib/selectize-rails/version.rb#1
module Selectize; end

# source://selectize-rails//lib/selectize-rails/version.rb#2
module Selectize::Rails; end

# source://selectize-rails//lib/selectize-rails/engine.rb#3
class Selectize::Rails::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.8.4/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://selectize-rails//lib/selectize-rails/version.rb#3
Selectize::Rails::VERSION = T.let(T.unsafe(nil), String)
