# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `selectize-rails` gem.
# Please instead update this file by running `bin/tapioca gem selectize-rails`.

# typed: true

module Selectize; end
module Selectize::Rails; end
class Selectize::Rails::Engine < ::Rails::Engine; end
Selectize::Rails::VERSION = T.let(T.unsafe(nil), String)
