# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `themes_on_rails` gem.
# Please instead update this file by running `bin/tapioca gem themes_on_rails`.

# source://themes_on_rails//lib/themes_on_rails/version.rb#1
module ThemesOnRails
  class << self
    # source://themes_on_rails//lib/themes_on_rails.rb#9
    def all; end
  end
end

# source://themes_on_rails//lib/themes_on_rails/action_controller.rb#2
class ThemesOnRails::ActionController
  # @return [ActionController] a new instance of ActionController
  #
  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#52
  def initialize(controller, theme); end

  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#69
  def prefix_path; end

  # Returns the value of attribute theme_name.
  #
  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#3
  def theme_name; end

  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#63
  def theme_resolver; end

  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#57
  def theme_view_path; end

  private

  # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#75
  def _theme_name(theme); end

  class << self
    # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#6
    def apply_theme(controller_class, theme, options = T.unsafe(nil)); end

    private

    # source://themes_on_rails//lib/themes_on_rails/action_controller.rb#42
    def before_filter_method(options); end
  end
end

# source://themes_on_rails//lib/themes_on_rails/controller_additions.rb#2
module ThemesOnRails::ControllerAdditions
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ThemesOnRails::ControllerAdditions::ClassMethods
end

# source://themes_on_rails//lib/themes_on_rails/controller_additions.rb#5
module ThemesOnRails::ControllerAdditions::ClassMethods
  # source://themes_on_rails//lib/themes_on_rails/controller_additions.rb#6
  def theme(theme, options = T.unsafe(nil)); end
end

# source://themes_on_rails//lib/themes_on_rails/engine.rb#4
class ThemesOnRails::Engine < ::Rails::Engine; end

# source://themes_on_rails//lib/themes_on_rails/version.rb#2
ThemesOnRails::VERSION = T.let(T.unsafe(nil), String)
