# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Standard::DropdownComponent::MenuComponent`.
# Please instead update this file by running `bin/tapioca dsl Standard::DropdownComponent::MenuComponent`.

class Standard::DropdownComponent::MenuComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
