# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ConfirmationMailer::HelperMethods`.
# Please instead update this file by running `bin/tapioca dsl ConfirmationMailer::HelperMethods`.

module ConfirmationMailer::HelperMethods
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
