exclude:
  - vendor/**/*

linters:
  LineLength:
    enabled: false

  ViewLength:
    enabled: false

  # Another one that we should fix but sometimes it's non-trivial. So,
  # putting aside for the time being
  IdNames:
    enabled: false

  RuboCop:
      enabled: true
      # These cops are incredibly noisy when it comes to HAML templates, so we
      # ignore them.
      ignored_cops:
        - Layout/ArgumentAlignment
        - Layout/IndentationConsistency
        - Layout/BlockAlignment
        - Layout/EndAlignment
        - Lint/Void
        - Layout/ElseAlignment
        - Layout/EndOfLine
        - Layout/IndentationWidth
        - Layout/TrailingWhitespace
        - Layout/TrailingEmptyLines
        - Metrics/BlockLength
        - Metrics/BlockNesting
        - Layout/LineLength
        - Naming/FileName
        - Style/FrozenStringLiteralComment
        - Style/IfUnlessModifier
        - Style/Next
        - Style/WhileUntilModifier
        - Style/StringLiteralsInInterpolation
        - Layout/CommentIndentation
        - Sorbet/FalseSigil
        - Sorbet/TrueSigil
        - Sorbet/StrictSigil
