#!/usr/local/bin/bash

export PLANNING_ROOT="/data/vhost/www.planningalerts.com/"
export PLANNING_BACKUPS="$PLANNING_ROOT/backups/"
export DEPLOYMENT_LOG_DIRECTORY="$PLANNING_ROOT/logs/"
export DEPLOYMENT_LOG="$DEPLOYMENT_LOG_DIRECTORY/deployment_log"

export BACKUP_DIRECTORY_NAME="planningalerts_backup_`date +%F_%Hh%Mm%Ss`"

export BACKUP_DIRECTORY="$PLANNING_BACKUPS$BACKUP_DIRECTORY_NAME/"

export TEAM_EMAIL="team@planningalerts.com"

$SHELL deployment_script_common
