dsl:
  exclude:
  - ActiveRecordFixtures
  halt_upon_load_error: false
  workers: 1
gem:
  exclude:
    - spoom
    - tapioca
    - rbi
    - sprockets-rails
    - sprockets
    - sassc-rails
    - capistrano-tagging3
    - skylight
