# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `tapioca require`.

# typed: strict
require "active_support/core_ext/integer/time"
require "administrate/base_dashboard"
require "administrate/custom_dashboard"
require "administrate/field/base"
require "bootsnap/setup"
require "bundler"
# require "bundler/capistrano"
require "bundler/setup"
require "devise/orm/active_record"
require "rack/throttle"
require "rails/all"
require "rest-client"
require "rss/1.0"
require "rss/2.0"
require "rubygems"
require "sidekiq/web"
require "sorbet-runtime"
require "zlib"
require "active_support/core_ext/securerandom"
require "geocoder/stores/active_record"
require "rails_autolink/helpers"
