# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionMailer::Rescuable`.
# Please instead update this file by running `bin/tapioca dsl ActionMailer::Rescuable`.

# typed: true

module ActionMailer::Rescuable
  mixes_in_class_methods ::ActiveSupport::Rescuable::ClassMethods
end
