# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AlertComponent`.
# Please instead update this file by running `bin/tapioca dsl AlertComponent`.


class AlertComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
