# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ConfirmationMailer`.
# Please instead update this file by running `bin/tapioca dsl ConfirmationMailer`.

class ConfirmationMailer
  class << self
    sig { params(object: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def confirm(object); end
  end
end
