# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DropdownComponent`.
# Please instead update this file by running `bin/tapioca dsl DropdownComponent`.

class DropdownComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
