# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GenerateSitemapService`.
# Please instead update this file by running `bin/tapioca dsl GenerateSitemapService`.

# typed: true

class GenerateSitemapService
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
