# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MapWithRadiusComponent`.
# Please instead update this file by running `bin/tapioca dsl MapWithRadiusComponent`.


class MapWithRadiusComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
