# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReplyToDoNotReplyMailer`.
# Please instead update this file by running `bin/tapioca dsl ReplyToDoNotReplyMailer`.

class ReplyToDoNotReplyMailer
  class << self
    sig { params(mail: ::Mail::Message).returns(::ActionMailer::MessageDelivery) }
    def reply(mail); end
  end
end
