# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UpdateApiUsageJob`.
# Please instead update this file by running `bin/tapioca dsl UpdateApiUsageJob`.

class UpdateApiUsageJob
  class << self
    sig { params(api_key: ::ApiKey, date: ::Date).returns(T.any(UpdateApiUsageJob, FalseClass)) }
    def perform_later(api_key:, date:); end

    sig { params(api_key: ::ApiKey, date: ::Date).void }
    def perform_now(api_key:, date:); end
  end
end
