# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveRecord::AttributeMethods::Dirty`.
# Please instead update this file by running `bin/tapioca dsl ActiveRecord::AttributeMethods::Dirty`.

# typed: true

module ActiveRecord::AttributeMethods::Dirty
  mixes_in_class_methods ::ActiveModel::AttributeMethods::ClassMethods
end
