# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SupportMailer::HelperMethods`.
# Please instead update this file by running `bin/tapioca dsl SupportMailer::HelperMethods`.

module SupportMailer::HelperMethods
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
