# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BootstrapForm::Inputs::DatetimeField`.
# Please instead update this file by running `bin/tapioca dsl BootstrapForm::Inputs::DatetimeField`.

# typed: true

module BootstrapForm::Inputs::DatetimeField
  mixes_in_class_methods ::BootstrapForm::Inputs::Base::ClassMethods
end
