# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BootstrapForm::Inputs::SearchField`.
# Please instead update this file by running `bin/tapioca dsl BootstrapForm::Inputs::SearchField`.

# typed: true

module BootstrapForm::Inputs::SearchField
  mixes_in_class_methods ::BootstrapForm::Inputs::Base::ClassMethods
end
