#
# MySQL
#

# default: &default
#   adapter: mysql2
#   # To use utf8mb4 with mysql 5.6 we need to enable innodb_large_prefix. See
#   # https://edgeguides.rubyonrails.org/configuring.html#configuring-a-mysql-or-mariadb-database
#   encoding: utf8mb4
#   # We're using an older collation because it's supported on mysql 5.6
#   # which is what we're currently using in production.
#   collation: utf8mb4_general_ci
#   # Set pool to the same as the sidekiq concurrency
#   pool: 10
#   # This setting is only really necessary if using mysql 5.7.5 or later
#   variables:
#     sql_mode: TRADITIONAL

# development:
#   <<: *default
#   host: database
#   database: pa_development
#   username: root
#   password: password
#   reconnect: false

# test:
#   <<: *default
#   host: database
#   database: pa_test
#   username: root
#   password: password
#   reconnect: false

# production:
#   <<: *default
#   host: <%= Rails.application.credentials.dig(:database, :mysql, :host) %>
#   database: pa-production
#   # For mysql read-only access (during maintenance switch out to the two lines below)
#   # username: pa-production-readonly
#   # password: "<%= Rails.application.credentials.dig(:database, :mysql, :password_readonly) %>"
#   username: pa-production
#   password: "<%= Rails.application.credentials.dig(:database, :mysql, :password) %>"

#
# Postgres
#

default: &default
  adapter: postgresql
  encoding: unicode
  # Set pool to the same as the sidekiq concurrency
  pool: 10

development:
  <<: *default
  host: postgres
  database: pa_development
  username: postgres
  password: password

test:
  <<: *default
  host: postgres
  database: pa_test
  username: postgres
  password: password

production:
  <<: *default
  host: "<%= Rails.application.credentials.dig(:database, :postgres, :host) %>"
  database: pa-production
  # For postgres read-only access (during maintenance switch out the two lines below)
  # username: pa-production-readonly
  # password: "<%= Rails.application.credentials.dig(:database, :postgres, :password_readonly) %>"
  username: pa-production
  password: "<%= Rails.application.credentials.dig(:database, :postgres, :password) %>"
