default: &default
  adapter: postgis
  encoding: unicode
  # Set pool to the same as the sidekiq concurrency
  pool: 10

development:
  <<: *default
  host: postgres
  database: pa_development
  username: postgres
  password: password

test:
  <<: *default
  host: postgres
  database: pa_test
  username: postgres
  password: password

production:
  <<: *default
  host: "<%= Rails.application.credentials.dig(:database, :postgres, :host) %>"
  database: pa-production
  # For postgres read-only access (during maintenance switch out the two lines below)
  # username: pa-production-readonly
  # password: "<%= Rails.application.credentials.dig(:database, :postgres, :password_readonly) %>"
  username: pa-production
  password: "<%= Rails.application.credentials.dig(:database, :postgres, :password) %>"
