elasticsearch_snapshot:
  # TODO: Switch back to 3:20 am
  cron: "every day at 6:30 am Australia/Sydney"
  class: "ElasticsearchSnapshotJob"
  description: "Take a snapshot of planningalerts indexes on elasticsearch and store on S3"