# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Rails::ApplicationController::HelperMethods`.
# Please instead update this file by running `bin/tapioca dsl Rails::ApplicationController::HelperMethods`.

module Rails::ApplicationController::HelperMethods
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
