# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Parts; end
module ActiveSupport::Dependencies::ModuleConstMissing; end
module Net::SSH::Loggable; end
module Rails::Dom::Testing::Assertions::SelectorAssertions::CountDescribable; end
module URI::Escape; end
