# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::ContainerComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::ContainerComponent`.

class Tailwind::ContainerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
