# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::HeadingComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::HeadingComponent`.

class Tailwind::HeadingComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
