# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::IconComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::IconComponent`.

class Tailwind::IconComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
