# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::NavItemComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::NavItemComponent`.

class Tailwind::NavItemComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
