# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::PanelListItem`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::PanelListItem`.

class Tailwind::PanelListItem
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
