# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::QuotedBlock`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::QuotedBlock`.

class Tailwind::QuotedBlock
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
