# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::SelectLinks`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::SelectLinks`.

class Tailwind::SelectLinks
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
