# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::ShareButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::ShareButtonComponent`.

class Tailwind::ShareButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
