# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tailwind::StreetviewComponent`.
# Please instead update this file by running `bin/tapioca dsl Tailwind::StreetviewComponent`.

class Tailwind::StreetviewComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
